
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Sex = 0F,
    Gpa = 96F,
    Physics = 76F,
    Math = 80F,
    Art = 0F,
    Analytic = 1F,
    Construct = 1F,
    Electric = 1F,
    Mechanic = 0F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Specialty with predicted Specialty from sample data...\n\n");


Console.WriteLine($"Sex: {0F}");
Console.WriteLine($"Gpa: {96F}");
Console.WriteLine($"Physics: {76F}");
Console.WriteLine($"Math: {80F}");
Console.WriteLine($"Art: {0F}");
Console.WriteLine($"Analytic: {1F}");
Console.WriteLine($"Construct: {1F}");
Console.WriteLine($"Electric: {1F}");
Console.WriteLine($"Mechanic: {0F}");
Console.WriteLine($"Specialty: {@"A"}");


Console.WriteLine($"\n\nPredicted Specialty: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

